### ISSUE TITLE
Error with build script locally

### ISSUE THREAD

**Issue by tedw** [swup/swup#144]
Hi there,

Big fan of Swup, nice work! I was going to submit a PR to fix an error in IE 10, swapping out [`dataset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) ([caniuse.com](https://caniuse.com/#feat=dataset&search=dataset)) for `getAttribute()`/`setAttribute()`, but got the following error when trying to run `npm run build`:

```
/Users/twhitehead/Sites/swup/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/twhitehead/Sites/swup/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/twhitehead/Sites/swup/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/twhitehead/Sites/swup/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swup@2.0.4 build: `webpack-cli`
npm ERR! Exit status 1
```

Do you have any idea why this is happening? I tried running it with Node 8.15.0 and 10.15.3. The compile script ran fine.

Thanks!

**Comment by tedw** [comment]
Never mind, upgrading to the latest version of webpack-cli fixed it! https://github.com/webpack/webpack-cli/issues/607#issuecomment-424389911

Will submit PRs for this and IE 10 thing shortly.
