### ISSUE TITLE
Cannot integrate Gia Plugin with swup 4.1

### ISSUE THREAD

**Issue by joh-sch** [swup/swup#751]
**Description**

I'm trying to create a swup instance with the Gia plugin enabled. Launching the instance without the plugin works just fine, but when adding an instance of it to the `plugins` option, the instance throws an error and transitions are broken.

Code to launch swup instance:

```js
import Foo from "../components/Foo";

const components = { Foo };
const swupOptions = {
  plugins: [ new SwupGiaPlugin({ components }) ],
};
const swupInstance = new Swup(swupOptions);
```

Resulting in the following error:

```js
index.modern.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'containers')
    at get containers [as containers] (index.modern.js:1:414)
    at Zt.mountComponents (index.modern.js:1:940)
    at Zt.mount (index.modern.js:1:816)
    at St.mt [as use] (Swup.modern.js:1:12873)
    at Swup.modern.js:1:15339
    at Array.forEach (<anonymous>)
    at St.enable (Swup.modern.js:1:15323)
    at new St (Swup.modern.js:1:15016)
    at t.value (appMod-swup.js:108:26)
    at t.value (appMod-swup.js:71:10)
```

<img width="685" alt="Screenshot 2023-07-29 at 14 55 52" src="https://github.com/swup/swup/assets/39758027/95e58486-7145-4e27-a7a4-84f65a508b65">

**How to reproduce the issue**

Create a new swup instance that is being passed an instance of the Gia plugin in the array set as its `plugins` option's value.

A reduced test case that displays the error can be found here: https://codesandbox.io/s/swup-4-gia-plugin-test-h5wvgh
Open the code sandbox link, click on the *page 1* link in the examples navigation and observe the console, it will display the same error mentioned above.

**Context and environment**

swup version: 4.1
Browser: Chrome, Version 115.0.5790.114 (Official Build) (arm64)
Device: Apple MacBook Pro M1 Max

**Before creating this issue...**

- [x] Have you provided all helpful information available?
- [x] Have you checked closed issues for similar/related problems?
- [x] Have you considered creating a demo so we can help you better?

**Comment by hirasso** [comment]
Thank you for this detailed bug report! This likely slipped through during our recent updates for swup4. 

Would you like to try your hand at fixing this in a PR?

**Comment by hirasso** [comment]
Actually, which version of Gia Plugin are you using?
